// <auto-generated />
namespace CommentProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Added_MainCommentId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_MainCommentId));
        
        string IMigrationMetadata.Id
        {
            get { return "202002091653180_Added_MainCommentId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
